[package]
name = "molt-fs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[features]
default = ["format"]
format = []

[dependencies]
molt-block.workspace = true
molt-core.workspace = true

[dev-dependencies]
criterion = "0.7"

[lib]
bench = false

[[bench]]
name = "volume"
harness = false
