#![no_std]

//! RISC-V supervisor boot adaptation and hardware implementations.
//!
//! OpenSBI enters `_start`, which prepares the stack and `.bss` before calling
//! the kernel entry generated by [`entry_point!`].

#[cfg(target_arch = "riscv64")]
mod ap;
#[cfg(target_arch = "riscv64")]
mod csr;
// SBI error decoding remains host-testable.
mod error;
// Reading a device tree is byte parsing, so it stays testable on the host too.
pub mod fdt;
#[cfg(target_arch = "riscv64")]
mod paging;
#[cfg(target_arch = "riscv64")]
mod percpu;
// The `satp` MODE encoding is arithmetic on one CSR field, so it is tested on
// the host like the SBI codes and the device tree.
pub mod satp;
#[cfg(target_arch = "riscv64")]
mod sbi;
#[cfg(target_arch = "riscv64")]
mod trap;

/// Defines the kernel entry called by this crate's `_start` shim.
#[macro_export]
macro_rules! entry_point {
    ($path:path) => {
        /// Rust boot entry invoked once by `_start` on the initialized stack.
        #[unsafe(no_mangle)]
        extern "C" fn __molt_riscv_main(hartid: usize, device_tree: usize) -> ! {
            $crate::start(hartid, device_tree, $path)
        }
    };
}

pub use error::SbiError;
#[cfg(target_arch = "riscv64")]
pub use imp::{Console, RiscV, SbiSerial, start};

#[cfg(target_arch = "riscv64")]
mod imp {
    use core::arch::{asm, global_asm};
    use core::fmt::Write as _;

    use molt_arch::memory::{Device, Rights, Span};
    use molt_arch::{
        BootInfo, ConfigSpace, CpuId, DeviceMapper, Entry, ExitStatus, FRAME_SIZE, FabricError,
        FrameCursor, InterruptFabric, Local, MappingError, MemoryMap, MemoryRegion,
        MemoryRegionKind, Mmio, MsiMessage, Platform, PlatformError, SerialPort, SerialWriter,
        Sink, Smp, SmpError, Stack, va,
    };

    use crate::{ap, csr, fdt, paging, percpu, sbi, trap};

    /// End of the QEMU `virt` board's default RAM, used only when there is no
    /// device tree to read it from.
    const RAM_END: u64 = 0x8800_0000;

    global_asm!(
        r#"
.section .text._start, "ax"
.global _start
_start:
    csrw    sie, zero          // mask supervisor interrupts until the vector is set
    csrci   sstatus, 2         // keep traps disabled during setup
    la      sp, __molt_stack_top
    la      t0, __bss_start    // bounds are doubleword-aligned
    la      t1, __bss_end
0:
    bgeu    t0, t1, 1f
    sd      zero, 0(t0)
    addi    t0, t0, 8
    j       0b
1:
    call    __molt_riscv_main  // OpenSBI supplies hartid and device tree
2:
    wfi                        // park if the entry returns
    j       2b
"#
    );

    /// Builds the architecture-neutral boot state and starts the shared kernel.
    #[doc(hidden)]
    pub fn start(
        hartid: usize,
        device_tree: usize,
        kernel: fn(BootInfo<'_>, &mut RiscV) -> !,
    ) -> ! {
        // The boot core takes its block before anything else runs on it: `tp` is
        // how every layer above finds anything, including the panic path.
        // SAFETY: this is the hart firmware entered, and this is its only call.
        unsafe { percpu::attach(CpuId::BOOT, hartid as u64) };
        let memory_map = RiscVMemoryMap::new(device_tree);
        // Every mode this kernel enables identity-maps physical memory, so the
        // physical offset is zero whichever one the hart took.
        let boot_info = BootInfo::new(&memory_map, Some(0));
        // The pointer is kept rather than read here: the tree is the only
        // description of where PCI lives, and nothing has asked for PCI yet.
        let mut platform = RiscV::new().with_device_tree(device_tree);
        kernel(boot_info, &mut platform)
    }

    #[cfg(target_os = "none")]
    #[panic_handler]
    fn panic(info: &core::panic::PanicInfo<'_>) -> ! {
        molt_arch::panic_handler::<RiscV>(info)
    }

    /// Usable RAM after the loaded image, bounded by the bank it sits in.
    struct RiscVMemoryMap {
        usable_start: u64,
        usable_end: u64,
    }

    impl RiscVMemoryMap {
        /// Reads how much RAM the board has instead of assuming a board.
        ///
        /// The constant this replaces was the QEMU `virt` default, which made
        /// `-m` a lie in both directions: more RAM went unused, and less would
        /// have had the frame allocator hand out addresses that decode to
        /// nothing. Firmware knows the answer and puts it in the tree, so the
        /// constant is now only what a hart entered without a tree falls back
        /// to — the machine that shape of boot is likeliest to be.
        fn new(device_tree: usize) -> Self {
            unsafe extern "C" {
                static __kernel_end: u8;
            }
            let end = (&raw const __kernel_end) as u64;
            let usable_start = (end + FRAME_SIZE - 1) & !(FRAME_SIZE - 1);
            // The image is inside the bank that matters, which is what makes
            // the bank identifiable on a board that has several.
            // SAFETY: firmware's pointer, or zero, which `ram_at` refuses
            // before any load.
            let bank = unsafe { fdt::ram_at(device_tree, end) };
            // A bank ending mid-frame would otherwise become a frame that is
            // half real.
            let usable_end = bank.map_or(RAM_END, |bank| bank.end()) & !(FRAME_SIZE - 1);
            Self { usable_start, usable_end }
        }
    }

    impl MemoryMap for RiscVMemoryMap {
        fn len(&self) -> usize {
            1
        }

        fn region(&self, index: usize) -> Option<MemoryRegion> {
            match index {
                0 => Some(MemoryRegion::new(
                    self.usable_start,
                    self.usable_end,
                    MemoryRegionKind::Usable,
                )),
                _ => None,
            }
        }
    }

    /// Concrete services for the current RISC-V supervisor boot target.
    pub struct RiscV {
        serial: SbiSerial,
        /// The device tree pointer OpenSBI passed in `a1`, or zero when it
        /// passed none. Firmware leaves the blob in memory for the life of the
        /// kernel, so keeping the address is enough; keeping a borrow of it
        /// would tie the platform to a lifetime nothing else in `Platform` has.
        device_tree: usize,
    }

    impl RiscV {
        pub const fn new() -> Self {
            Self { serial: SbiSerial::new(), device_tree: 0 }
        }

        /// Records where firmware left the flattened device tree.
        pub const fn with_device_tree(mut self, address: usize) -> Self {
            self.device_tree = address;
            self
        }

        /// Numbers the harts the device tree listed.
        ///
        /// A blob that says nothing about `/cpus` describes one hart as far as
        /// molt is concerned: [`percpu::declare`] always keeps the core already
        /// running, so the failure costs parallelism and nothing else.
        fn declare_cpus(&self) {
            let mut listed = [0; percpu::MAX];
            // SAFETY: as in `config_space` — firmware's pointer, still mapped,
            // borrowed for this call only.
            let found = unsafe { fdt::harts_at(self.device_tree, &mut listed) };
            percpu::declare(&listed[..found.unwrap_or(0)], percpu::this().hart());
        }
    }

    impl Default for RiscV {
        fn default() -> Self {
            Self::new()
        }
    }

    impl DeviceMapper for RiscV {
        fn map_device(
            &mut self,
            window: Device,
            rights: Rights,
        ) -> Result<Mmio<'static>, MappingError> {
            paging::map_device(window, rights)
        }
    }

    /// No message-signalled interrupts on this platform, and no pretending.
    ///
    /// A QEMU `virt` machine started without `aia=aplic-imsic` has no MSI
    /// controller at all: there is no address a device could write to raise an
    /// interrupt, so there is no honest [`MsiMessage`] to return. PCI devices
    /// there deliver INTx through the PLIC instead, which is a different
    /// delivery path — a shared, level-triggered line claimed and completed at
    /// the controller — and Stage 2.2 does not build it. Returning
    /// [`FabricError::Unsupported`] makes a driver that needs a vector say so;
    /// inventing a message would make it write into whatever sits at the
    /// address we invented.
    impl InterruptFabric for RiscV {
        fn allocate(&mut self, _cpu: CpuId) -> Result<(u16, MsiMessage), FabricError> {
            Err(FabricError::Unsupported)
        }

        fn release(&mut self, _line: u16) -> Result<(), FabricError> {
            Err(FabricError::Unsupported)
        }
    }

    // SAFETY: `attach` gave this core an element of a static array, which nothing
    // else installs and which outlives every core.
    unsafe impl Local for RiscV {
        unsafe fn install(block: *mut ()) {
            percpu::this().set_block(block);
        }

        fn block() -> *mut () {
            percpu::this().block()
        }
    }

    impl Smp for RiscV {
        fn cpus(&self) -> u16 {
            percpu::count()
        }

        fn cpu(&self) -> CpuId {
            percpu::this().cpu()
        }

        /// # Safety
        ///
        /// As the trait says: `stack` is this hart's alone from here on.
        unsafe fn start(&mut self, cpu: CpuId, stack: Stack, entry: Entry) -> Result<(), SmpError> {
            // SAFETY: forwarded.
            unsafe { ap::start(cpu, stack, entry) }
        }

        /// Rings the doorbell, and only sends the interrupt when it was not
        /// already ringing: an unanswered wake is one the target has yet to
        /// look at, and a second one tells it nothing the first did not.
        ///
        /// Waking this hart rings and stops there. The flag is what [`park`]
        /// reads, so the ring is the point; an interrupt to oneself would only
        /// arrive where the caller already is.
        ///
        /// [`park`]: Self::park
        fn wake(&self, cpu: CpuId) -> Result<(), SmpError> {
            let target = percpu::of(cpu).ok_or(SmpError::Unknown)?;
            if target.ring() && cpu != self.cpu() {
                sbi::send_ipi(target.hart()).map_err(|_| SmpError::Refused)?;
            }
            Ok(())
        }

        /// The SBI timer, rearmed by its own handler: every hart arms its own.
        fn ticking(&self) -> Result<(), SmpError> {
            trap::ticking();
            Ok(())
        }

        fn ticks(&self) -> u64 {
            trap::ticks()
        }

        /// Arms before halting: the doorbell is checked with interrupts off, so
        /// a wake that arrived while the caller decided it had no work is taken
        /// here rather than slept through.
        fn park(&self) {
            // SAFETY: clearing `sstatus.SIE` around the check only delays traps;
            // `wfi` resumes on a pending interrupt whether or not they are on.
            unsafe {
                csr::disable_interrupts();
                if percpu::this().answered() {
                    csr::enable_interrupts();
                } else {
                    csr::enable_interrupts();
                    asm!("wfi", options(nomem, nostack));
                }
            }
        }
    }

    impl Platform for RiscV {
        type Serial = SbiSerial;

        fn serial(&mut self) -> &mut Self::Serial {
            &mut self.serial
        }

        fn initialize(&mut self, boot_info: &BootInfo<'_>) -> Result<(), PlatformError> {
            self.serial.init();
            let console = self.serial.console();
            let _ = writeln!(SerialWriter::new(&mut self.serial), "MOLT_SBI_CONSOLE: {console:?}");

            trap::init();
            // SAFETY: the trap vector is installed, so a doorbell has somewhere
            // to land.
            unsafe { csr::enable_software_interrupts() };
            self.declare_cpus();
            paging::init(boot_info)?;
            // Which mode the hart took decides how much address space there is
            // to hand out, so it is reported rather than assumed.
            if let Some(mode) = paging::mode() {
                let _ = writeln!(
                    SerialWriter::new(&mut self.serial),
                    "MOLT_SATP_MODE: {} ({} address bits)",
                    mode.name(),
                    mode.bits(),
                );
            }
            Ok(())
        }

        fn verify_exception_path(&mut self) -> bool {
            trap::verify_breakpoint()
        }

        fn verify_owned_mapping(&mut self, boot_info: &BootInfo<'_>) -> Result<(), PlatformError> {
            paging::verify_owned_mapping(boot_info)
        }

        fn verify_image_protection(
            &mut self,
            boot_info: &BootInfo<'_>,
        ) -> Result<(), PlatformError> {
            paging::verify_image_protection(boot_info)
        }

        fn verify_device_window(&mut self, boot_info: &BootInfo<'_>) -> Result<(), PlatformError> {
            paging::verify_device_window(boot_info)
        }

        /// The ECAM window the device tree describes, if firmware described one.
        ///
        /// Every failure collapses to [`PlatformError::MissingConfigSpace`]:
        /// the caller's only question is whether there is a configuration
        /// space to enumerate, and a blob with bad magic and a blob without a
        /// PCI node are the same answer to it. The parse detail stays in
        /// [`fdt::FdtError`](crate::fdt::FdtError) for whoever is debugging.
        fn config_space(
            &mut self,
            _boot_info: &BootInfo<'_>,
        ) -> Result<ConfigSpace, PlatformError> {
            // SAFETY: `device_tree` is zero — refused without a load — or the
            // pointer OpenSBI passed to `_start`, which firmware leaves mapped
            // and immutable, and the tree is only borrowed for this call.
            unsafe { fdt::config_space_at(self.device_tree) }
                .map_err(|_| PlatformError::MissingConfigSpace)
        }

        /// Interrupt routing is not built on this platform; see
        /// [`InterruptFabric`] for why there is nothing to route yet.
        fn route_interrupts(&mut self, _sink: &'static dyn Sink) -> Result<(), PlatformError> {
            Err(PlatformError::Fabric(FabricError::Unsupported))
        }

        /// Both halves come from the probes [`paging::init`] already ran: the
        /// address width from the `satp` MODE the hart accepted, the tag width
        /// from the ASID bits it kept.
        fn address_space(&self) -> Option<va::Widths> {
            Some(va::Widths::new(paging::mode()?.bits(), paging::asid_bits()?))
        }

        fn free_frames(&self) -> Option<FrameCursor> {
            paging::free_frames()
        }

        fn claim_ram(
            &mut self,
            boot_info: &BootInfo<'_>,
            count: u64,
        ) -> Result<Span, PlatformError> {
            paging::claim_ram(boot_info, count)
        }

        fn terminate(&mut self, status: ExitStatus) -> ! {
            sbi::shutdown(matches!(status, ExitStatus::Success))
        }
    }

    /// Selected SBI console transport.
    #[derive(Clone, Copy, Debug, Eq, PartialEq)]
    pub enum Console {
        /// Not yet selected.
        Unprobed,
        /// Error-reporting debug console extension.
        Debug,
        /// Byte-oriented legacy console.
        Legacy,
    }

    pub struct SbiSerial {
        console: Console,
    }

    impl SbiSerial {
        pub const fn new() -> Self {
            Self { console: Console::Unprobed }
        }

        pub fn console(&self) -> Console {
            self.console
        }
    }

    impl Default for SbiSerial {
        fn default() -> Self {
            Self::new()
        }
    }

    impl SerialPort for SbiSerial {
        fn init(&mut self) {
            if self.console == Console::Unprobed {
                self.console =
                    if sbi::has_debug_console() { Console::Debug } else { Console::Legacy };
            }
        }

        fn write_byte(&mut self, byte: u8) {
            self.write_bytes(&[byte]);
        }

        fn write_bytes(&mut self, bytes: &[u8]) {
            self.init();
            if self.console == Console::Debug {
                let mut written = 0;
                while written < bytes.len() {
                    match sbi::debug_console_write(&bytes[written..]) {
                        // Zero progress on a non-empty buffer would spin forever.
                        Ok(0) | Err(_) => {
                            self.console = Console::Legacy;
                            break;
                        }
                        Ok(count) => written += count,
                    }
                }
                if self.console == Console::Debug {
                    return;
                }
                for &byte in &bytes[written..] {
                    sbi::console_putchar(byte);
                }
                return;
            }
            for &byte in bytes {
                sbi::console_putchar(byte);
            }
        }
    }
}
