#![no_std]

//! RISC-V supervisor boot adaptation and hardware implementations.
//!
//! OpenSBI enters `_start`, which prepares the stack and `.bss` before calling
//! the kernel entry generated by [`entry_point!`].

#[cfg(target_arch = "riscv64")]
mod csr;
// SBI error decoding remains host-testable.
mod error;
// Reading a device tree is byte parsing, so it stays testable on the host too.
pub mod fdt;
#[cfg(target_arch = "riscv64")]
mod paging;
#[cfg(target_arch = "riscv64")]
mod sbi;
#[cfg(target_arch = "riscv64")]
mod trap;

/// Defines the kernel entry called by this crate's `_start` shim.
#[macro_export]
macro_rules! entry_point {
    ($path:path) => {
        /// Rust boot entry invoked once by `_start` on the initialized stack.
        #[unsafe(no_mangle)]
        extern "C" fn __molt_riscv_main(hartid: usize, device_tree: usize) -> ! {
            $crate::start(hartid, device_tree, $path)
        }
    };
}

pub use error::SbiError;
#[cfg(target_arch = "riscv64")]
pub use imp::{Console, RiscV, SbiSerial, start};

#[cfg(target_arch = "riscv64")]
mod imp {
    use core::arch::{asm, global_asm};
    use core::fmt::Write as _;

    use molt_arch::memory::{Device, Rights};
    use molt_arch::{
        BootInfo, ConfigSpace, DeviceMapper, ExitStatus, FRAME_SIZE, FabricError, InterruptFabric,
        MappingError, MemoryMap, MemoryRegion, MemoryRegionKind, Mmio, MsiMessage, Platform,
        PlatformError, SerialPort, SerialWriter, Sink,
    };

    use crate::{csr, fdt, paging, sbi, trap};

    /// End of the QEMU `virt` board's default RAM.
    const RAM_END: u64 = 0x8800_0000;

    global_asm!(
        r#"
.section .text._start, "ax"
.global _start
_start:
    csrw    sie, zero          // mask supervisor interrupts until the vector is set
    csrci   sstatus, 2         // keep traps disabled during setup
    la      sp, __molt_stack_top
    la      t0, __bss_start    // bounds are doubleword-aligned
    la      t1, __bss_end
0:
    bgeu    t0, t1, 1f
    sd      zero, 0(t0)
    addi    t0, t0, 8
    j       0b
1:
    call    __molt_riscv_main  // OpenSBI supplies hartid and device tree
2:
    wfi                        // park if the entry returns
    j       2b
"#
    );

    /// Builds the architecture-neutral boot state and starts the shared kernel.
    #[doc(hidden)]
    pub fn start(
        _hartid: usize,
        device_tree: usize,
        kernel: fn(BootInfo<'_>, &mut RiscV) -> !,
    ) -> ! {
        let memory_map = RiscVMemoryMap::new();
        // Sv39 identity-maps physical memory, so the physical offset is zero.
        let boot_info = BootInfo::new(&memory_map, Some(0));
        // The pointer is kept rather than read here: the tree is the only
        // description of where PCI lives, and nothing has asked for PCI yet.
        let mut platform = RiscV::new().with_device_tree(device_tree);
        kernel(boot_info, &mut platform)
    }

    #[cfg(target_os = "none")]
    #[panic_handler]
    fn panic(info: &core::panic::PanicInfo<'_>) -> ! {
        molt_arch::panic_handler::<RiscV>(info)
    }

    /// Usable RAM after the loaded image.
    struct RiscVMemoryMap {
        usable_start: u64,
    }

    impl RiscVMemoryMap {
        fn new() -> Self {
            unsafe extern "C" {
                static __kernel_end: u8;
            }
            let end = (&raw const __kernel_end) as u64;
            let usable_start = (end + FRAME_SIZE - 1) & !(FRAME_SIZE - 1);
            Self { usable_start }
        }
    }

    impl MemoryMap for RiscVMemoryMap {
        fn len(&self) -> usize {
            1
        }

        fn region(&self, index: usize) -> Option<MemoryRegion> {
            match index {
                0 => Some(MemoryRegion::new(self.usable_start, RAM_END, MemoryRegionKind::Usable)),
                _ => None,
            }
        }
    }

    /// Concrete services for the current RISC-V supervisor boot target.
    pub struct RiscV {
        serial: SbiSerial,
        /// The device tree pointer OpenSBI passed in `a1`, or zero when it
        /// passed none. Firmware leaves the blob in memory for the life of the
        /// kernel, so keeping the address is enough; keeping a borrow of it
        /// would tie the platform to a lifetime nothing else in `Platform` has.
        device_tree: usize,
    }

    impl RiscV {
        pub const fn new() -> Self {
            Self { serial: SbiSerial::new(), device_tree: 0 }
        }

        /// Records where firmware left the flattened device tree.
        pub const fn with_device_tree(mut self, address: usize) -> Self {
            self.device_tree = address;
            self
        }
    }

    impl Default for RiscV {
        fn default() -> Self {
            Self::new()
        }
    }

    impl DeviceMapper for RiscV {
        fn map_device(
            &mut self,
            window: Device,
            rights: Rights,
        ) -> Result<Mmio<'static>, MappingError> {
            paging::map_device(window, rights)
        }
    }

    /// No message-signalled interrupts on this platform, and no pretending.
    ///
    /// A QEMU `virt` machine started without `aia=aplic-imsic` has no MSI
    /// controller at all: there is no address a device could write to raise an
    /// interrupt, so there is no honest [`MsiMessage`] to return. PCI devices
    /// there deliver INTx through the PLIC instead, which is a different
    /// delivery path — a shared, level-triggered line claimed and completed at
    /// the controller — and Stage 2.2 does not build it. Returning
    /// [`FabricError::Unsupported`] makes a driver that needs a vector say so;
    /// inventing a message would make it write into whatever sits at the
    /// address we invented.
    impl InterruptFabric for RiscV {
        fn allocate(&mut self) -> Result<(u16, MsiMessage), FabricError> {
            Err(FabricError::Unsupported)
        }

        fn release(&mut self, _line: u16) -> Result<(), FabricError> {
            Err(FabricError::Unsupported)
        }
    }

    impl Platform for RiscV {
        type Serial = SbiSerial;

        fn serial(&mut self) -> &mut Self::Serial {
            &mut self.serial
        }

        fn initialize(&mut self, boot_info: &BootInfo<'_>) -> Result<(), PlatformError> {
            self.serial.init();
            let console = self.serial.console();
            let _ = writeln!(SerialWriter::new(&mut self.serial), "MOLT_SBI_CONSOLE: {console:?}");

            trap::init();
            paging::init(boot_info)
        }

        fn verify_exception_path(&mut self) -> bool {
            trap::verify_breakpoint()
        }

        fn verify_owned_mapping(&mut self, boot_info: &BootInfo<'_>) -> Result<(), PlatformError> {
            paging::verify_owned_mapping(boot_info)
        }

        fn verify_image_protection(
            &mut self,
            boot_info: &BootInfo<'_>,
        ) -> Result<(), PlatformError> {
            paging::verify_image_protection(boot_info)
        }

        fn verify_device_window(&mut self, boot_info: &BootInfo<'_>) -> Result<(), PlatformError> {
            paging::verify_device_window(boot_info)
        }

        /// The ECAM window the device tree describes, if firmware described one.
        ///
        /// Every failure collapses to [`PlatformError::MissingConfigSpace`]:
        /// the caller's only question is whether there is a configuration
        /// space to enumerate, and a blob with bad magic and a blob without a
        /// PCI node are the same answer to it. The parse detail stays in
        /// [`fdt::FdtError`](crate::fdt::FdtError) for whoever is debugging.
        fn config_space(
            &mut self,
            _boot_info: &BootInfo<'_>,
        ) -> Result<ConfigSpace, PlatformError> {
            // SAFETY: `device_tree` is zero — refused without a load — or the
            // pointer OpenSBI passed to `_start`, which firmware leaves mapped
            // and immutable, and the tree is only borrowed for this call.
            unsafe { fdt::config_space_at(self.device_tree) }
                .map_err(|_| PlatformError::MissingConfigSpace)
        }

        /// Interrupt routing is not built on this platform; see
        /// [`InterruptFabric`] for why there is nothing to route yet.
        fn route_interrupts(&mut self, _sink: &'static dyn Sink) -> Result<(), PlatformError> {
            Err(PlatformError::Fabric(FabricError::Unsupported))
        }

        fn arm_timer(&mut self, initial_count: u32) -> Result<(), PlatformError> {
            // Arm one absolute deadline before unmasking its interrupt.
            let deadline = csr::time().wrapping_add(u64::from(initial_count));
            sbi::set_timer(deadline);
            // SAFETY: `initialize` installed the trap vector before any timer arms.
            unsafe {
                csr::enable_timer_interrupts();
            }
            Ok(())
        }

        fn monotonic_ticks(&self) -> u64 {
            trap::ticks()
        }

        fn wait_for_timer_change(&mut self, previous: u64) {
            while trap::ticks() == previous {
                // SAFETY: with the timer interrupt unmasked, `wfi` resumes on the tick.
                unsafe {
                    asm!("wfi", options(nomem, nostack));
                }
            }
        }

        fn terminate(&mut self, status: ExitStatus) -> ! {
            sbi::shutdown(matches!(status, ExitStatus::Success))
        }
    }

    /// Selected SBI console transport.
    #[derive(Clone, Copy, Debug, Eq, PartialEq)]
    pub enum Console {
        /// Not yet selected.
        Unprobed,
        /// Error-reporting debug console extension.
        Debug,
        /// Byte-oriented legacy console.
        Legacy,
    }

    pub struct SbiSerial {
        console: Console,
    }

    impl SbiSerial {
        pub const fn new() -> Self {
            Self { console: Console::Unprobed }
        }

        pub fn console(&self) -> Console {
            self.console
        }
    }

    impl Default for SbiSerial {
        fn default() -> Self {
            Self::new()
        }
    }

    impl SerialPort for SbiSerial {
        fn init(&mut self) {
            if self.console == Console::Unprobed {
                self.console =
                    if sbi::has_debug_console() { Console::Debug } else { Console::Legacy };
            }
        }

        fn write_byte(&mut self, byte: u8) {
            self.write_bytes(&[byte]);
        }

        fn write_bytes(&mut self, bytes: &[u8]) {
            self.init();
            if self.console == Console::Debug {
                let mut written = 0;
                while written < bytes.len() {
                    match sbi::debug_console_write(&bytes[written..]) {
                        // Zero progress on a non-empty buffer would spin forever.
                        Ok(0) | Err(_) => {
                            self.console = Console::Legacy;
                            break;
                        }
                        Ok(count) => written += count,
                    }
                }
                if self.console == Console::Debug {
                    return;
                }
                for &byte in &bytes[written..] {
                    sbi::console_putchar(byte);
                }
                return;
            }
            for &byte in bytes {
                sbi::console_putchar(byte);
            }
        }
    }
}
