#![no_std]

//! RISC-V supervisor boot adaptation and hardware implementations.
//!
//! OpenSBI enters `_start`, which prepares the stack and `.bss` before calling
//! the kernel entry generated by [`entry_point!`].

#[cfg(target_arch = "riscv64")]
mod csr;
// SBI error decoding remains host-testable.
mod error;
#[cfg(target_arch = "riscv64")]
mod paging;
#[cfg(target_arch = "riscv64")]
mod sbi;
#[cfg(target_arch = "riscv64")]
mod trap;

/// Defines the kernel entry called by this crate's `_start` shim.
#[macro_export]
macro_rules! entry_point {
    ($path:path) => {
        /// Rust boot entry invoked once by `_start` on the initialized stack.
        #[unsafe(no_mangle)]
        extern "C" fn __molt_riscv_main(hartid: usize, device_tree: usize) -> ! {
            $crate::start(hartid, device_tree, $path)
        }
    };
}

pub use error::SbiError;
#[cfg(target_arch = "riscv64")]
pub use imp::{Console, RiscV, SbiSerial, start};

#[cfg(target_arch = "riscv64")]
mod imp {
    use core::arch::{asm, global_asm};
    use core::fmt::Write as _;

    use molt_arch::{
        BootInfo, ExitStatus, FRAME_SIZE, MemoryMap, MemoryRegion, MemoryRegionKind, Platform,
        PlatformError, SerialPort, SerialWriter,
    };

    use crate::{csr, paging, sbi, trap};

    /// End of the QEMU `virt` board's default RAM.
    const RAM_END: u64 = 0x8800_0000;

    global_asm!(
        r#"
.section .text._start, "ax"
.global _start
_start:
    csrw    sie, zero          // mask supervisor interrupts until the vector is set
    csrci   sstatus, 2         // keep traps disabled during setup
    la      sp, __molt_stack_top
    la      t0, __bss_start    // bounds are doubleword-aligned
    la      t1, __bss_end
0:
    bgeu    t0, t1, 1f
    sd      zero, 0(t0)
    addi    t0, t0, 8
    j       0b
1:
    call    __molt_riscv_main  // OpenSBI supplies hartid and device tree
2:
    wfi                        // park if the entry returns
    j       2b
"#
    );

    /// Builds the architecture-neutral boot state and starts the shared kernel.
    #[doc(hidden)]
    pub fn start(
        _hartid: usize,
        _device_tree: usize,
        kernel: fn(BootInfo<'_>, &mut RiscV) -> !,
    ) -> ! {
        let memory_map = RiscVMemoryMap::new();
        // Sv39 identity-maps physical memory, so the physical offset is zero.
        let boot_info = BootInfo::new(&memory_map, Some(0));
        let mut platform = RiscV::new();
        kernel(boot_info, &mut platform)
    }

    #[cfg(target_os = "none")]
    #[panic_handler]
    fn panic(info: &core::panic::PanicInfo<'_>) -> ! {
        molt_arch::panic_handler::<RiscV>(info)
    }

    /// Usable RAM after the loaded image.
    struct RiscVMemoryMap {
        usable_start: u64,
    }

    impl RiscVMemoryMap {
        fn new() -> Self {
            unsafe extern "C" {
                static __kernel_end: u8;
            }
            let end = (&raw const __kernel_end) as u64;
            let usable_start = (end + FRAME_SIZE - 1) & !(FRAME_SIZE - 1);
            Self { usable_start }
        }
    }

    impl MemoryMap for RiscVMemoryMap {
        fn len(&self) -> usize {
            1
        }

        fn region(&self, index: usize) -> Option<MemoryRegion> {
            match index {
                0 => Some(MemoryRegion::new(self.usable_start, RAM_END, MemoryRegionKind::Usable)),
                _ => None,
            }
        }
    }

    /// Concrete services for the current RISC-V supervisor boot target.
    pub struct RiscV {
        serial: SbiSerial,
    }

    impl RiscV {
        pub const fn new() -> Self {
            Self { serial: SbiSerial::new() }
        }
    }

    impl Default for RiscV {
        fn default() -> Self {
            Self::new()
        }
    }

    impl Platform for RiscV {
        type Serial = SbiSerial;

        fn serial(&mut self) -> &mut Self::Serial {
            &mut self.serial
        }

        fn initialize(&mut self, boot_info: &BootInfo<'_>) -> Result<(), PlatformError> {
            self.serial.init();
            let console = self.serial.console();
            let _ = writeln!(SerialWriter::new(&mut self.serial), "MOLT_SBI_CONSOLE: {console:?}");

            trap::init();
            paging::init(boot_info)
        }

        fn verify_exception_path(&mut self) -> bool {
            trap::verify_breakpoint()
        }

        fn verify_owned_mapping(&mut self, boot_info: &BootInfo<'_>) -> Result<(), PlatformError> {
            paging::verify_owned_mapping(boot_info)
        }

        fn verify_image_protection(
            &mut self,
            boot_info: &BootInfo<'_>,
        ) -> Result<(), PlatformError> {
            paging::verify_image_protection(boot_info)
        }

        fn verify_device_window(&mut self, boot_info: &BootInfo<'_>) -> Result<(), PlatformError> {
            paging::verify_device_window(boot_info)
        }

        fn arm_timer(&mut self, initial_count: u32) -> Result<(), PlatformError> {
            // Arm one absolute deadline before unmasking its interrupt.
            let deadline = csr::time().wrapping_add(u64::from(initial_count));
            sbi::set_timer(deadline);
            // SAFETY: `initialize` installed the trap vector before any timer arms.
            unsafe {
                csr::enable_timer_interrupts();
            }
            Ok(())
        }

        fn monotonic_ticks(&self) -> u64 {
            trap::ticks()
        }

        fn wait_for_timer_change(&mut self, previous: u64) {
            while trap::ticks() == previous {
                // SAFETY: with the timer interrupt unmasked, `wfi` resumes on the tick.
                unsafe {
                    asm!("wfi", options(nomem, nostack));
                }
            }
        }

        fn terminate(&mut self, status: ExitStatus) -> ! {
            sbi::shutdown(matches!(status, ExitStatus::Success))
        }
    }

    /// Selected SBI console transport.
    #[derive(Clone, Copy, Debug, Eq, PartialEq)]
    pub enum Console {
        /// Not yet selected.
        Unprobed,
        /// Error-reporting debug console extension.
        Debug,
        /// Byte-oriented legacy console.
        Legacy,
    }

    pub struct SbiSerial {
        console: Console,
    }

    impl SbiSerial {
        pub const fn new() -> Self {
            Self { console: Console::Unprobed }
        }

        pub fn console(&self) -> Console {
            self.console
        }
    }

    impl Default for SbiSerial {
        fn default() -> Self {
            Self::new()
        }
    }

    impl SerialPort for SbiSerial {
        fn init(&mut self) {
            if self.console == Console::Unprobed {
                self.console =
                    if sbi::has_debug_console() { Console::Debug } else { Console::Legacy };
            }
        }

        fn write_byte(&mut self, byte: u8) {
            self.write_bytes(&[byte]);
        }

        fn write_bytes(&mut self, bytes: &[u8]) {
            self.init();
            if self.console == Console::Debug {
                let mut written = 0;
                while written < bytes.len() {
                    match sbi::debug_console_write(&bytes[written..]) {
                        // Zero progress on a non-empty buffer would spin forever.
                        Ok(0) | Err(_) => {
                            self.console = Console::Legacy;
                            break;
                        }
                        Ok(count) => written += count,
                    }
                }
                if self.console == Console::Debug {
                    return;
                }
                for &byte in &bytes[written..] {
                    sbi::console_putchar(byte);
                }
                return;
            }
            for &byte in bytes {
                sbi::console_putchar(byte);
            }
        }
    }
}
