[package]
name = "molt-exec"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[lib]
bench = false

[dependencies]
molt-core.workspace = true

[dev-dependencies]
criterion = "0.7"

[[bench]]
name = "task"
harness = false

[[bench]]
name = "timer"
harness = false
