[package]
name = "molt-shell-domain"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false
build = "build.rs"

[dependencies]
molt-core.workspace = true
molt-fs.workspace = true
molt-shell.workspace = true
molt-user.workspace = true

[lints]
workspace = true

[[bin]]
name = "molt-shell-domain"
path = "src/main.rs"
test = false
bench = false
