[package]
name = "molt-rt"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[lib]
bench = false

[dependencies]
limen.workspace = true
molt-core.workspace = true


[dev-dependencies]
limen = { workspace = true, features = ["threads"] }
criterion = "0.7"

[[bench]]
name = "task"
harness = false

[[bench]]
name = "timer"
harness = false
