[package]
name = "molt-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[lib]
bench = false

[dev-dependencies]
limen = { workspace = true, features = ["threads"] }
criterion = "0.7"


[[bench]]
name = "ring"
harness = false

[[bench]]
name = "scheduler"
harness = false

[dependencies]
limen.workspace = true
